/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-21 01:45:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.recomCourse;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dao.MemberDao;
import java.util.ArrayList;
import data.dto.TourSpotDto;
import data.dto.CourseDto;
import java.util.List;
import data.dao.TourSpotDao;
import data.dao.RecomCourseDao;

public final class detailRecomCourse_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("data.dao.MemberDao");
    _jspx_imports_classes.add("data.dao.RecomCourseDao");
    _jspx_imports_classes.add("data.dto.TourSpotDto");
    _jspx_imports_classes.add("data.dto.CourseDto");
    _jspx_imports_classes.add("data.dao.TourSpotDao");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Bagel+Fat+One&family=Dongle:wght@300&family=East+Sea+Dokdo&family=Gamja+Flower&family=Gowun+Dodum&family=Nanum+Gothic+Coding&family=Nanum+Pen+Script&family=Orbit&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("	href=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css\" />\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

// dao 호출
RecomCourseDao RecomCourseDao = new RecomCourseDao();
TourSpotDao TourSpotDao = new TourSpotDao();

String name = request.getParameter("name");

// name값을 받아서 recomCourse 출력
List<CourseDto> recomlist = RecomCourseDao.getRecomCourseName(name);

System.out.println(name);

// 받아온 CourseDto의 name값을 이용하여 tour_seq 가져오기 (RecomCourse table)
// 가져온 tour_ser를 이용하여 TourSpotDto의 자료 가져오기 (RecomCourse table -> TourSpot table)
List<TourSpotDto> spotlist = new ArrayList<TourSpotDto>();

for (int i = 0; i < recomlist.size(); i++) {
	String tour_seq = recomlist.get(i).getTour_seq(); // 순차적으로 name에 해당하는 Tour_seq의 값을 받아온다. 
	TourSpotDto tdto = TourSpotDao.getdata(tour_seq);
	spotlist.add(tdto);

}

String loginok=(String)session.getAttribute("loginok");
String myid=(String)session.getAttribute("myid");

MemberDao MemberDao = new MemberDao();

String root=request.getContextPath();


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);\r\n");
      out.write("\r\n");
      out.write("body * { \r\n");
      out.write(" font-family: 'Jeju Gothic', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".slick {\r\n");
      out.write("	margin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("/*이전,다음*/\r\n");
      out.write(".slick-arrow {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	transform: translateY(-50%);\r\n");
      out.write("	z-index: 5\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slick-prev {\r\n");
      out.write("	left: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slick-next {\r\n");
      out.write("	right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slick-list {\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-box {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	margin: 0 5px;\r\n");
      out.write("	display:flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("    justify-content:center;\r\n");
      out.write("    align-items:center;\r\n");
      out.write("    padding: 10px 10px 10px 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".image-box1 {\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	aspect-ratio: 1;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-box img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slick-prev, .slick-next {\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	border: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slick-prev:after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	width: 50px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	background-image: url(");
      out.print(root);
      out.write("/jeju/left.svg);\r\n");
      out.write("	background-size: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slick-next:after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	width: 50px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	display: block;\r\n");
      out.write("	background-image: url(");
      out.print(root);
      out.write("/jeju/left.svg);\r\n");
      out.write("	background-size: 100%;\r\n");
      out.write("	transform: scaleX(-1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".photoname{\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	transform: translate(-50%, -50%);\r\n");
      out.write("	text-shadow: 2px 2px 2px gray;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-style {\r\n");
      out.write("	padding: 0 20px 20px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-in-style {\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	box-shadow: 2px 3px 9px 3px rgba(87, 88, 89, .25);\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	border: 2px solid #1976D2;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: column;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title>div {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.title>div p {\r\n");
      out.write("	margin-bottom: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.tnum {\r\n");
      out.write("	border-radius: 100px;\r\n");
      out.write("	background-color: #1976D2;\r\n");
      out.write("	width: 20px;\r\n");
      out.write("	height: 20px;\r\n");
      out.write("	margin-right: 5px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.detailbg {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	background-color: #cfcfcf;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	border-radius:20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.taddr {\r\n");
      out.write("	display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img-box {\r\n");
      out.write("	width: 500px;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	background: #eee;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("	overflow: hideen;\r\n");
      out.write("	margin: 30px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img-boxclick{\r\n");
      out.write("	background-color: blue;\r\n");
      out.write("	opacity: 0.4;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img-box>img {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tag-box {\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-wrap: wrap;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tag-box>p {\r\n");
      out.write("	margin: 0 8px 0 0;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #000;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.text-box, div.tag-box {\r\n");
      out.write("	padding: 1 20px 10px 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.container {\r\n");
      out.write("	align-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.backgound {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	top: 100px;\r\n");
      out.write("	left: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".heartBtn {\r\n");
      out.write("	position: fixed;\r\n");
      out.write("	right: 10%;\r\n");
      out.write("	bottom: 10%;\r\n");
      out.write("	border: transparent;\r\n");
      out.write("	background-color: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bi-heart {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bi-heart-fill {\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	color: red;	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.bg{\r\n");
      out.write("	margin: 100px 100px 100px 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".t-order{\r\n");
      out.write("	border: 2px solid #1976D2;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("	width: 30px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"likes\">\r\n");
      out.write("		<button class=\"heartBtn\" name=\"");
      out.print(name);
      out.write("\">\r\n");
      out.write("			<i class=\"bi bi-heart\"></i>\r\n");
      out.write("		</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"bg\">\r\n");
      out.write("		<div class=\"detailbg\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"slick\">\r\n");
      out.write("				");

				for (int i=0;i<spotlist.size();i++) {
					TourSpotDto TourSpotDto = spotlist.get(i);
					//System.out.println(dto.getName());
				
      out.write("\r\n");
      out.write("				<div class='list-box'>\r\n");
      out.write("					<div class=\"t-order\">\r\n");
      out.write("						<p>");
      out.print(i+1 );
      out.write("</p>\r\n");
      out.write("					</div>					\r\n");
      out.write("					<div class='image-box1'>\r\n");
      out.write("						<img alt=\"\" src=\"");
      out.print(root );
      out.write("/jeju/");
      out.print(TourSpotDto.getPhoto());
      out.write("\" class=\"spotimg\" seq=\"");
      out.print(TourSpotDto.getSeq());
      out.write("\" num=");
      out.print(i+1 );
      out.write(">\r\n");
      out.write("						<p class=\"photoname\">");
      out.print(TourSpotDto.getName());
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				");

				}
				
      out.write("\r\n");
      out.write("			</div>\r\n");

				for (int i = 0; i < 1; i++) {
					TourSpotDto TourSpotDto = spotlist.get(i);
					//System.out.println(dto.getName());
				
      out.write("\r\n");
      out.write("			<div class='box-style'>\r\n");
      out.write("				<div class='box-in-style' id=\"detailcontent\">\r\n");
      out.write("					<div class=\"title\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=\"tnum\">\r\n");
      out.write("								<p>");
      out.print(i+1 );
      out.write("</p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<p>");
      out.print(TourSpotDto.getName() );
      out.write("</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=\"taddr\">\r\n");
      out.write("								<p>주소: ");
      out.print(TourSpotDto.getAddr() );
      out.write("</p>\r\n");
      out.write("								&nbsp;\r\n");
      out.write("								<p>|</p>\r\n");
      out.write("								&nbsp;\r\n");
      out.write("								<p>hp: ");
      out.print(TourSpotDto.getHp() );
      out.write("</p>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class='img-box'>\r\n");
      out.write("						<img alt=\"\" src=\"");
      out.print(root );
      out.write("/jeju/");
      out.print(TourSpotDto.getPhoto());
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"text-box\">\r\n");
      out.write("						<p>");
      out.print(TourSpotDto.getIntro() );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class='tag-box'>\r\n");
      out.write("						<p>#");
      out.print(TourSpotDto.getArea() );
      out.write("</p>\r\n");
      out.write("						<p>#");
      out.print(TourSpotDto.getTheme() );
      out.write("</p>\r\n");
      out.write("						<p>#");
      out.print(TourSpotDto.getMain_cat() );
      out.write("</p>\r\n");
      out.write("						<p>#");
      out.print(TourSpotDto.getSub_cat() );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
				}
				
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		/* $('.slick').slick(); */\r\n");
      out.write("\r\n");
      out.write("		$(function() {\r\n");
      out.write("			$('.slick').slick({\r\n");
      out.write("				dots : false, // 하부 button, 누를 시 해당 사진으로 이동하는 버튼  \r\n");
      out.write("				infinite : false,\r\n");
      out.write("				speed : 300, // 움직이는 속도\r\n");
      out.write("				slidesToShow : 4, // 한페이지에 보여지는 사진 갯수\r\n");
      out.write("				slidesToScroll : 1, // 버튼 눌렀을 시에 넘어가는 사진 갯수\r\n");
      out.write("				arrow : false,\r\n");
      out.write("				prevArrow : \"<button type='button' class='slick-prev pull-left'></button>\",\r\n");
      out.write("				nextArrow : \"<button type='button' class='slick-next pull-right'></button>\"\r\n");
      out.write("			});\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		$(\".heartBtn\").click(function() {\r\n");
      out.write("			var name = $(this).attr(\"name\");\r\n");
      out.write("			var loginok=\"");
      out.print(loginok);
      out.write("\";\r\n");
      out.write("			/* alert(loginok); */\r\n");
      out.write("			if(loginok==\"null\") {\r\n");
      out.write("				var confirmLogin = confirm(\"로그인이 필요한 페이지입니다. 로그인하시겠습니까?\");\r\n");
      out.write("				if (confirmLogin) {\r\n");
      out.write("					// 사용자가 확인을 클릭한 경우 로그인 페이지로 이동\r\n");
      out.write("					window.location.href = \"index.jsp?main=recomCourse/recomLoginForm.jsp?name=\"+name;\r\n");
      out.write("				} else {\r\n");
      out.write("					// 사용자가 취소를 클릭한 경우 현재 페이지에 머물도록 함\r\n");
      out.write("				} s\r\n");
      out.write("			} else {\r\n");
      out.write("				if($(this).find(\".bi-heart\")){\r\n");
      out.write("					$(this).find(\"i\").removeClass(\"bi-heart\");\r\n");
      out.write("					$(this).find(\"i\").addClass(\"bi-heart-fill\");\r\n");
      out.write("				} else {\r\n");
      out.write("					$(this).find(\"i\").addClass(\"bi-heart\");\r\n");
      out.write("					$(this).find(\"i\").removeClass(\"bi-heart-fill\");\r\n");
      out.write("				}\r\n");
      out.write("				/* location.href=\"likesAjax.jsp?name=\"+name; */\r\n");
      out.write("			} \r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		});\r\n");
      out.write("		var previousClickedElement = null;\r\n");
      out.write("\r\n");
      out.write("		$(\"img.spotimg\").click(function() {\r\n");
      out.write("			var seq = $(this).attr(\"seq\");\r\n");
      out.write("			var num = $(this).attr(\"num\");\r\n");
      out.write("			\r\n");
      out.write("			 \r\n");
      out.write("				var currentClickedElement = $(this);\r\n");
      out.write("\r\n");
      out.write("				// 이전 클릭된 요소와 현재 클릭된 요소의 값을 비교\r\n");
      out.write("				if (previousClickedElement !== null && previousClickedElement[0] !== currentClickedElement[0]) {\r\n");
      out.write("				// 이전 클릭된 요소와 현재 클릭된 요소의 값이 다를 때 class 제거\r\n");
      out.write("				previousClickedElement.removeClass(\"img-boxclick\");\r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("				// 현재 클릭된 요소에 class 추가\r\n");
      out.write("				currentClickedElement.addClass(\"img-boxclick\");\r\n");
      out.write("\r\n");
      out.write("				// 현재 클릭된 요소를 이전 클릭된 요소로 설정\r\n");
      out.write("				previousClickedElement = currentClickedElement;\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			/* $(this).parent().parent().find(\".image-box1\").addClass(\"img-boxclick\"); */\r\n");
      out.write("			// alert(seq);\r\n");
      out.write("			// alert(num);\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				dataType:\"json\",\r\n");
      out.write("				url:\"");
      out.print(root);
      out.write("/recomCourse/detailAjax.jsp\",\r\n");
      out.write("				data:{\"seq\":seq,\"num\":num},\r\n");
      out.write("				success:function(data){\r\n");
      out.write("					// alert(data.seq);\r\n");
      out.write("					\r\n");
      out.write("					var s=\"<div class='title'>\";\r\n");
      out.write("					s+=\"<div>\";\r\n");
      out.write("					s+=\"<div class='tnum'>\";\r\n");
      out.write("					s+=\"<p>\"+data.num+\"</p>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("					s+=\"<p>\"+data.name+\"</p>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("					s+=\"<div>\";\r\n");
      out.write("					s+=\"<div class='taddr'>\";\r\n");
      out.write("					s+=\"<p>주소: \"+data.addr+\"</p>&nbsp;\";\r\n");
      out.write("					s+=\"<p>|</p>&nbsp;\";\r\n");
      out.write("					s+=\"<p>hp: \"+data.hp+\"</p>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("					s+=\"<div class='img-box'>\";\r\n");
      out.write("					s+=\"<img alt='' src='");
      out.print(root);
      out.write("/jeju/\"+data.photo+\"'>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("					s+=\"<div class='text-box'>\";\r\n");
      out.write("					s+=\"<p>\"+data.intro+\"</p>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("					s+=\"<div class='tag-box'>\";\r\n");
      out.write("					s+=\"<p>#\"+data.area+\"</p>\";\r\n");
      out.write("					s+=\"<p>#\"+data.theme+\"</p>\";\r\n");
      out.write("					s+=\"<p>#\"+data.main_cat+\"</p>\";\r\n");
      out.write("					s+=\"<p>#\"+data.sub_cat+\"</p>\";\r\n");
      out.write("					s+=\"</div>\";\r\n");
      out.write("\r\n");
      out.write("					$(\"#detailcontent\").html(s); \r\n");
      out.write("				}\r\n");
      out.write("\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
