/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-21 01:37:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.dao.MemberDao;

public final class menu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dao.MemberDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");

	String root=request.getContextPath();
	String myid=(String)session.getAttribute("myid");

      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cute+Font&family=Diphylleia&family=Dokdo&family=Nanum+Brush+Script&family=Nanum+Gothic+Coding&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(root);
      out.write("/menu/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(root);
      out.write("/menu/js/function.js\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");

   String loginok = (String)session.getAttribute("loginok");

   MemberDao dao = new MemberDao();
   String name = dao.getName(myid);

      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<!-- <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\"> -->\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Cute+Font&family=Diphylleia&family=Dokdo&family=Nanum+Brush+Script&family=Nanum+Gothic+Coding&family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(root);
      out.write("/menu/js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(root);
      out.write("/menu/js/function.js\"></script>\r\n");
      out.write("<title>Jeju do it</title>\r\n");
      out.write("<style>\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);\r\n");
      out.write("\r\n");
      out.write("span * {\r\n");
      out.write("    font-family: 'OAGothic-ExtraBold';\r\n");
      out.write("    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/OAGothic-ExtraBold.woff2') format('woff2');\r\n");
      out.write("    font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#ttop {\r\n");
      out.write("   margin-top: -18px;\r\n");
      out.write("   height: 80px;\r\n");
      out.write("   width: 1690px;\r\n");
      out.write("   background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topmenu {\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color: #696969;\r\n");
      out.write("   display: block;\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   font-family: 'Jeju Gothic', sans-serif;\r\n");
      out.write("   margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu a{\r\n");
      out.write("   text-decoration: none;\r\n");
      out.write("   color: #696969;\r\n");
      out.write("   display: block;\r\n");
      out.write("   font-size: 20px;\r\n");
      out.write("   font-family: 'Jeju Gothic', sans-serif;\r\n");
      out.write("   margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu a:hover{\r\n");
      out.write("	background-color: gray;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("   \r\n");
      out.write("#ttop ul li {\r\n");
      out.write("   list-style: none;\r\n");
      out.write("   float: left;\r\n");
      out.write("   line-height: 30px;\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".submenu{\r\n");
      out.write("   height: 0;\r\n");
      out.write("   overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#ttop:hover .submenu {\r\n");
      out.write("  height: 250px;\r\n");
      out.write("  transition-duration: 1s;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("nav ul li a:hover{\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("   $(function(){\r\n");
      out.write("      \r\n");
      out.write("      $(\"#ttop\").mouseover(function(){\r\n");
      out.write("         $(\".dv1\").css(\"height\",\"400px\").css(\"background-color\",\"#F5F5F5\").css(\"transition\",\"all 0.5s ease-in-out\");\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(\"#ttop\").mouseout(function(){\r\n");
      out.write("         $(\".dv1\").css(\"height\",\"0px\").css(\"background-color\",\"white\").css(\"transition\",\"all 0.5s ease-in-out\");\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("      $(\"#myCourseMenu\").click(function(){\r\n");
      out.write("          if(");
      out.print(loginok);
      out.write("==null){\r\n");
      out.write("             var confirmLogin = confirm(\"로그인이 필요한 페이지입니다. 로그인하시겠습니까?\");\r\n");
      out.write("             if (confirmLogin) {\r\n");
      out.write("                // 사용자가 확인을 클릭한 경우 로그인 페이지로 이동\r\n");
      out.write("                window.location.href = \"");
      out.print(root );
      out.write("/index.jsp?main=login/loginForm.jsp\";\r\n");
      out.write("             } else {\r\n");
      out.write("                // 사용자가 취소를 클릭한 경우 현재 페이지에 머물도록 함\r\n");
      out.write("             }\r\n");
      out.write("          }\r\n");
      out.write("       });\r\n");
      out.write("   });\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<div class=\"dv1\" style=\"position: fixed; z-index:999; height: 0px; background-color: white;opacity: 0.97\">\r\n");
      out.write("   <nav id=\"ttop\" style=\"\">\r\n");
      out.write("   <ul class=\"t1\">\r\n");
      out.write("      <li><img src=\"jeju/logo.png\" style=\"width: 130px; height: 50px; margin-left: 40px; margin-top: 10px; cursor: pointer;\" onclick=\"location.href='");
      out.print(root);
      out.write("/index.jsp'\"></li>\r\n");
      out.write("      <li><a href=\"#\" class=\"topmenu\" style=\"width: 200px; margin-left: 80px;\">ABOUT 제주</a>\r\n");
      out.write("         <ul class=\"submenu\" style=\"margin-left: 40px;\">\r\n");
      out.write("         <a href=\"");
      out.print(root);
      out.write("/index.jsp?main=about/introduce.jsp\" style=\"font-size: 15px;\">제주 소개</a>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" class=\"topmenu\" style=\"width: 150px; margin-left: 10px;\">추천 코스</a>\r\n");
      out.write("         <ul class=\"submenu\" style=\"margin-left: -20px;\">\r\n");
      out.write("         <a href=\"");
      out.print(root);
      out.write("/index.jsp?main=recomCourse/recomCourseList.jsp\" style=\"font-size: 15px;\">테마</a>\r\n");
      out.write("         <a href=\"\" style=\"font-size: 15px;\">지역</a>\r\n");
      out.write("         </ul></li>\r\n");
      out.write("\r\n");
      out.write("     <li id=\"myCourseMenu\"><a href='");
      out.print( (loginok != null) ? (root + "/index.jsp?main=myCourse/myCourseMap.jsp&selTheme=oceanTab") : '#' );
      out.write("' \r\n");
      out.write("     class=\"topmenu\" style=\"width: 150px; margin-left: 20px;\">나만의 코스</a></li>\r\n");
      out.write("\r\n");
      out.write("      <li><a href=\"#\" class=\"topmenu\" style=\"width: 150px; margin-left: 10px;\">리뷰</a>\r\n");
      out.write("         <ul class=\"submenu\" style=\"margin-left: -10px;\">\r\n");
      out.write("         <a href=\"\" style=\"font-size: 15px;\">코스 리뷰</a>\r\n");
      out.write("         ");
 if(loginok==null) {
      out.write("\r\n");
      out.write("        	 <a href=\"index.jsp?main=tourReview/logoutTourSpotReviewList.jsp\" style=\"font-size: 15px;\">관광지 리뷰</a>\r\n");
      out.write("         \r\n");
      out.write("         ");
 } else if(loginok!=null) {
         
      out.write("  <a href=\"index.jsp?main=tourReview/tourSpotReviewList.jsp\" style=\"font-size: 15px;\">관광지 리뷰</a>");
} 
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"#\" class=\"topmenu\" style=\"width: 150px; margin-left: 5px;\">이벤트</a>\r\n");
      out.write("         <ul class=\"submenu\" style=\"margin-left: -20px;\">\r\n");
      out.write("         <a href=\"index.jsp?main=event/eventIng.jsp\" style=\"font-size: 15px;\">진행중 이벤트</a>\r\n");
      out.write("         <a href=\"index.jsp?main=event/eventEnd.jsp\" style=\"font-size: 15px;\">종료 이벤트</a>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </li>\r\n");
      out.write("         ");
 if(loginok==null) {
         
         
      out.write("\r\n");
      out.write("         \r\n");
      out.write("         ");
 } else if(loginok!=null) {
         
      out.write("   \r\n");
      out.write("          <li><a href=\"#\" class=\"topmenu\" style=\"width: 150px; margin-left: 15px;\">마이페이지</a>\r\n");
      out.write("         <ul  class=\"submenu\" style=\"margin-left: -10px;\">\r\n");
      out.write("         <a href=\"index.jsp?main=myPage/mypage.jsp\" style=\"font-size: 15px;\">나의 정보</a>\r\n");
      out.write("         <a href=\"index.jsp?main=myList/myList.jsp\" style=\"font-size: 15px;\">MY LIST</a>\r\n");
      out.write("         </ul>\r\n");
      out.write("         ");

         }
         
      out.write("\r\n");
      out.write("         \r\n");
      out.write("      ");

      if(loginok==null) {
      
      out.write("\r\n");
      out.write("      </li>\r\n");
      out.write("      <li><a href=\"");
      out.print(root );
      out.write("/index.jsp?main=login/loginForm.jsp\" class=\"topmenu\" style=\"width: 150px; margin-left: 15px; font-size: 14px;\">로그인</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      \r\n");
      out.write("      ");
 } else if(loginok!=null) {
      
      out.write("\r\n");
      out.write("      <li>\r\n");
      out.write("      <a href=\"");
      out.print(root );
      out.write("/index.jsp?main=login/logoutAction.jsp\" class=\"topmenu\" style=\"width: 150px; margin-left: 15px; font-size: 14px;\">로그아웃</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      ");
     
      }
      
      out.write("\r\n");
      out.write("     \r\n");
      out.write("   </ul>\r\n");
      out.write("    <form class=\"d-flex\" action=\"index.jsp?main=search/searchIndex.jsp\" method=\"post\">\r\n");
      out.write("        <input class=\"form-control me-2\" type=\"text\"  style=\"width: 120px; margin-left: 30px; margin-top: 20px;\" name=\"inputWords\" placeholder=\"Search\">\r\n");
      out.write("        <button class=\"btn btn-primary\" type=\"submit\" style=\"margin-top: 20px; background-color: #696969; border-color: #696969;\">Search</button>\r\n");
      out.write("      </form>\r\n");
      out.write("   </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
