/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-21 01:48:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tourReview;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import data.dto.TourSpotDto;
import java.util.List;
import data.dao.TourSpotDao;

public final class logoutTourSpotReviewForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

 
   // JavaScript 함수 정의
   void clearSelDay() {
   

   }

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("data.dto.TourSpotDto");
    _jspx_imports_classes.add("data.dao.TourSpotDao");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://fonts.googleapis.com/css2?family=Cute+Font&family=Dongle:wght@300&family=Gamja+Flower&family=Gowun+Batang&family=Gowun+Dodum&family=Hi+Melody&family=Nanum+Gothic&family=Nanum+Gothic+Coding&family=Nanum+Pen+Script&family=Poor+Story&family=Sunflower:wght@300&display=swap\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("   href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("   rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("\r\n");
 

String seq=request.getParameter("seq");
 TourSpotDao dao = new TourSpotDao();
TourSpotDto tourspotdto=dao.getdata(seq);
List<TourSpotDto> list = dao.selectTourSpot();

String root=request.getContextPath();


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script>\r\n");
      out.write("function openFileInput(){\r\n");
      out.write("   document.getElementById('image').click();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function readURL(input){\r\n");
      out.write("   if(input.files && input.files[0]){\r\n");
      out.write("      var reader = new FileReader();\r\n");
      out.write("      \r\n");
      out.write("      reader.onload = function(e)\r\n");
      out.write("      {\r\n");
      out.write("         $('#showing').attr('src',e.target.result);\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      reader.readAsDataURL(input.files[0]);\r\n");
      out.write("   }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   $(function(){\r\n");
      out.write("         $(\"div.over1\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-half star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("            //alert(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over2\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over3\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-half star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over4\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-fill star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over5\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-fill star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star-half star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over6\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-fill star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star-fill star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over7\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-fill star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star-fill star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star-half star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over8\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-fill star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star-fill star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star-fill star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over9\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-fill star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star-fill star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star-fill star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star-half star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("         $(\"div.over10\").click(function(){\r\n");
      out.write("            $(\"i.star1\").attr(\"class\",\"bi bi-star-fill star1\");\r\n");
      out.write("            $(\"i.star2\").attr(\"class\",\"bi bi-star-fill star2\");\r\n");
      out.write("            $(\"i.star3\").attr(\"class\",\"bi bi-star-fill star3\");\r\n");
      out.write("            $(\"i.star4\").attr(\"class\",\"bi bi-star-fill star4\");\r\n");
      out.write("            $(\"i.star5\").attr(\"class\",\"bi bi-star-fill star5\");\r\n");
      out.write("            var sv=$(this).attr(\"value\");\r\n");
      out.write("            $(\"#starInput\").val(sv);\r\n");
      out.write("         });\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write(".input-container {\r\n");
      out.write("   display: flex;\r\n");
      out.write("   justify-content: space-between;\r\n");
      out.write("   width: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("   width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photo {\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".select {\r\n");
      out.write("   display: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@import\r\n");
      out.write("   url(//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css);\r\n");
      out.write("\r\n");
      out.write(".rate {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   border: 0;\r\n");
      out.write("   margin-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rate>input {\r\n");
      out.write("   display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rate>label {\r\n");
      out.write("   float: right;\r\n");
      out.write("   color: #ddd\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rate>label:before {\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   font-size: 1rem;\r\n");
      out.write("   padding: .3rem .2rem;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   font-family: FontAwesome;\r\n");
      out.write("   content: \"\\f005 \";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rate .half:before {\r\n");
      out.write("   content: \"\\f089 \";\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   padding-right: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rate input:checked ~ label, .rate label:hover, .rate label:hover ~\r\n");
      out.write("   label {\r\n");
      out.write("   color: #f73c32 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rate input:checked+.rate label:hover, .rate input input:checked ~ label:hover,\r\n");
      out.write("   .rate input:checked ~ .rate label:hover ~ label, .rate label:hover ~\r\n");
      out.write("   input:checked ~ label {\r\n");
      out.write("   color: #f73c32 !important;\r\n");
      out.write("}\r\n");
      out.write(" div.over{\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("   }\r\n");
      out.write("   i{\r\n");
      out.write("      color: orange;\r\n");
      out.write("   }\r\n");
      out.write("   i.star1{\r\n");
      out.write("      width: 50px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      font-size: 50px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 0px;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("   }\r\n");
      out.write("   i.star2{\r\n");
      out.write("      width: 50px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      font-size: 50px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 50px;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("   }\r\n");
      out.write("   i.star3{\r\n");
      out.write("      width: 50px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      font-size: 50px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 100px;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("   }\r\n");
      out.write("   i.star4{\r\n");
      out.write("      width: 50px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      font-size: 50px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 150px;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("   }\r\n");
      out.write("   i.star5{\r\n");
      out.write("      width: 50px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      font-size: 50px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 200px;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("   }\r\n");
      out.write("   div.over1{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 0px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over2{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 25px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over3{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 50px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over4{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 75px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over5{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 100px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over6{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 125px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over7{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 150px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over8{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 175px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over9{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 200px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 100px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("   div.over10{\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 0px;\r\n");
      out.write("      left: 225px;\r\n");
      out.write("      width: 25px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      opacity: 0;\r\n");
      out.write("      z-index: 10;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- form action 수정 -->\r\n");
      out.write("   <form action=\"tourReview/logoutTourSpotReviewAction.jsp\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("      <input type=\"hidden\" name=\"stars\" value=\"\" id=\"starInput\">\r\n");
      out.write("      <table class=\"table table-bordered\"\r\n");
      out.write("         style=\"width: 1100px; height: 400px; margin-top: 100px; margin-left: 180px;\">\r\n");
      out.write("         <tr>\r\n");
      out.write("            <td>\r\n");
      out.write("            <img src=\"");
      out.print(root );
      out.write("/jeju/map.png\" id=\"showing\"\r\n");
      out.write("               onclick=\"openFileInput()\" alt=\"\" width=\"50px;\" class=\"image\"\r\n");
      out.write("               height=\"40px\" margin-top=\"10px\";> <input type=\"file\"\r\n");
      out.write("               class=\"image\" id=\"image\" style=\"visibility: hidden;\"\r\n");
      out.write("               onchange=\"readURL(this)\"> \r\n");
      out.write("      \r\n");
      out.write("         \r\n");
      out.write("            <div style=\"position: relative; cursor:pointer; width: 500px;height: 100px; margin-left:400px;\">\r\n");
      out.write("      <i class=\"bi bi-star star1\"></i>\r\n");
      out.write("      <div class=\"over over1\" value=0.5></div>\r\n");
      out.write("      <div class=\"over over2\" value=1></div>\r\n");
      out.write("      <i class=\"bi bi-star star2\"></i>\r\n");
      out.write("      <div class=\"over over3\" value=1.5></div>\r\n");
      out.write("      <div class=\"over over4\" value=2></div>\r\n");
      out.write("      <i class=\"bi bi-star star3\" ></i>\r\n");
      out.write("      <div class=\"over over5\" value=2.5></div>\r\n");
      out.write("      <div class=\"over over6\" value=3></div>\r\n");
      out.write("      <i class=\"bi bi-star star4\"></i>\r\n");
      out.write("      <div class=\"over over7\" value=3.5></div>\r\n");
      out.write("      <div class=\"over over8\" value=4></div>\r\n");
      out.write("      <i class=\"bi bi-star star5\"></i>\r\n");
      out.write("      <div class=\"over over9\" value=4.5></div>\r\n");
      out.write("      <div class=\"over over10\" value=5></div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <div class=\"select\" style=\"margin-left: 10px; width: 300px;\">\r\n");
      out.write("                  <br> <select id=\"theme\" class=\"form-select form-select-sm\"\r\n");
      out.write("                     style=\"width: 200px;\">\r\n");
      out.write("                     <option value=\"바다\" selected>바다</option>\r\n");
      out.write("                     <option value=\"산\">산</option>\r\n");
      out.write("                     <option value=\"올레길\">올레길</option>\r\n");
      out.write("                     <option value=\"섬\">섬</option>\r\n");
      out.write("                     <option value=\"체험\">체험</option>\r\n");
      out.write("                     <option value=\"음식\">음식</option>\r\n");
      out.write("                     <option value=\"숙박\">숙박</option>\r\n");
      out.write("                     <option value=\"쇼핑\">쇼핑</option>\r\n");
      out.write("                  </select> &nbsp;&nbsp;&nbsp;\r\n");
      out.write("\r\n");
      out.write("                  ");
      out.write("\r\n");
      out.write("                  <script>\r\n");
      out.write("      $(function(){            \r\n");
      out.write("      $(\"#selDay\").empty();\r\n");
      out.write("      \r\n");
      out.write("      var op_val=\"\";\r\n");
      out.write("      \r\n");
      out.write("      $(\"#theme\").on(\"change\",function(){\r\n");
      out.write("        var main_cat=$(this).val();\r\n");
      out.write("        var s=\"<select id='selDay' class='form-select form-select-sm' style='width:200px'>\";\r\n");
      out.write("        $.ajax({\r\n");
      out.write("          type:\"get\",\r\n");
      out.write("          url:\"tourReview/listSpot.jsp\",\r\n");
      out.write("          dataType:\"json\",\r\n");
      out.write("          data:{\"main_cat\":main_cat},\r\n");
      out.write("          success:function(res){\r\n");
      out.write("             $.each(res,function(i,e){\r\n");
      out.write("                s+=\"<option value='\"+e.name+\"'>\"+e.name+\"</option>\";\r\n");
      out.write("             });\r\n");
      out.write("             s+=\"</select>\";\r\n");
      out.write("            $(\"#sel2\").html(s);\r\n");
      out.write("            \r\n");
      out.write("            $(\"#selDay\").on(\"change\",function(){\r\n");
      out.write("                   op_val=$(this).val();\r\n");
      out.write("                   $(\"#op\").val(op_val);\r\n");
      out.write("                   \r\n");
      out.write("                   $.ajax({\r\n");
      out.write("                   	type:\"get\",\r\n");
      out.write("                   	url:\"tourReview/getPhoto.jsp\",\r\n");
      out.write("                   	dataType:\"json\",\r\n");
      out.write("                   	data:{\"op_val\":op_val,\"sort\":\"2\"},\r\n");
      out.write("                   	success:function(r){\r\n");
      out.write("                   		var p=\"<img src='jeju/\"+r.photo+\"' style='width:200px;height:200px;border-radius:20px;margin-left:100px'>\";\r\n");
      out.write("                   		$(\"#sel3\").html(p);\r\n");
      out.write("                   		$(\"#avg\").text(r.avg);\r\n");
      out.write("                   	}\r\n");
      out.write("                   	\r\n");
      out.write("                    });\r\n");
      out.write("                });\r\n");
      out.write("          }\r\n");
      out.write("        });\r\n");
      out.write("      });\r\n");
      out.write("      })\r\n");
      out.write("\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("         \r\n");
      out.write("                  <div id=\"sel2\"></div><div id=\"sel3\"></div><div id=\"avg\"></div>\r\n");
      out.write("                  \r\n");
      out.write("                  ");

                  {
                  }
                  
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("				    <input type=\"hidden\" name=\"op_val\" value=\"\" id=\"op\">\r\n");
      out.write("               <div class=\"input-container\" style=\"margin-left: 818px; width: 300px;\">\r\n");
      out.write("                  <input class=\"h\" type=\"hidden\" name=\"seq\" value=\"\"> <br>\r\n");
      out.write("                  <input class=\"form-control me-2\" name=\"nickname\" type=\"text\" style=\"width: 120px;\" required=\"required\" placeholder=\"닉네임\">&nbsp;&nbsp;\r\n");
      out.write("                  <input class=\"form-control me-2\" name=\"pass\" type=\"password\" style=\"width: 120px;\" required=\"required\" placeholder=\"비밀번호\">\r\n");
      out.write("                  <br>\r\n");
      out.write("               </div>\r\n");
      out.write("               <br>\r\n");
      out.write("               <input type=\"text\" name=\"title\" class=\"form-control\" style=\"width: 1100px; margin-left: 10px\" required=\"required\" placeholder=\"제목\">\r\n");
      out.write("               <br>\r\n");
      out.write("               <textarea style=\"width: 1100px; height: 150px; margin-left: 10px\" name=\"content\" required=\"required\" class=\"form-control\" placeholder=\"리뷰를 작성해주세요\"></textarea>\r\n");
      out.write("               <button class=\"btn btn-ouline-dark\" type=\"submit\" style=\"margin-top: 10px; margin-left: 1052px; border-color: #696969;\">등록</button>\r\n");
      out.write("            </td>\r\n");
      out.write("         </tr>\r\n");
      out.write("    \r\n");
      out.write("      </table>\r\n");
      out.write("   </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
