/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-21 01:56:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import data.dao.PopularSearchesDao;

public final class popularSearches_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("data.dao.PopularSearchesDao");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Dongle:wght@300&family=Nanum+Pen+Script&family=Noto+Serif+KR:wght@200&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("	@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);\r\n");
      out.write("\r\n");
      out.write("	@font-face {\r\n");
      out.write("    	font-family: 'OAGothic-ExtraBold';\r\n");
      out.write("    	src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/OAGothic-ExtraBold.woff2') format('woff2');\r\n");
      out.write("    	font-style: normal;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	#shape{\r\n");
      out.write("		margin: 40px 20px 40px 20px;\r\n");
      out.write("		background-color: #EEEEEE;\r\n");
      out.write("		padding: 15px 15px 15px 15px;\r\n");
      out.write("	}\r\n");
      out.write("	div.subject,span.pspan{\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	div.list,div.select,button.btn-success{\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("	div.ptop{\r\n");
      out.write("		font-size: 1.3em;\r\n");
      out.write("		margin-bottom: 12px;\r\n");
      out.write("	}\r\n");
      out.write("	@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);\r\n");
      out.write("\r\n");
      out.write("	body * { \r\n");
      out.write("		font-family: 'Jeju Gothic', sans-serif;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	$(function(){\r\n");
      out.write("		\r\n");
      out.write("		$(subjectDivs[0]).click(function(){\r\n");
      out.write("			showList(0);\r\n");
      out.write("			console.log(\"작동완\");\r\n");
      out.write("		});\r\n");
      out.write("		$(subjectDivs[1]).click(function(){\r\n");
      out.write("			showList(1);\r\n");
      out.write("		});\r\n");
      out.write("		$(subjectDivs[2]).click(function(){\r\n");
      out.write("			showList(2);\r\n");
      out.write("		});\r\n");
      out.write("		$(subjectDivs[3]).click(function(){\r\n");
      out.write("			showList(3);\r\n");
      out.write("		});\r\n");
      out.write("		$(\"i.pback\").click(function(){\r\n");
      out.write("			hideList();\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(buttonDivs[0]).on(\"click\",function(){\r\n");
      out.write("			var age_v=$(\"#age\").val();\r\n");
      out.write("			var s=\"<ol>\";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"get\",\r\n");
      out.write("				data:{\"age\":age_v},\r\n");
      out.write("				url:\"search/ageListProc.jsp\",\r\n");
      out.write("				dataType:\"json\",\r\n");
      out.write("				success:function(res){\r\n");
      out.write("					$.each(res, function(i,e){s+=\"<li>\"+e+\"</li>\";});\r\n");
      out.write("					s+=\"</ol>\";\r\n");
      out.write("					$(listDivs[0]).html(s);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			$(\"button.cancel\").trigger(\"click\");\r\n");
      out.write("		});\r\n");
      out.write("		$(buttonDivs[1]).on(\"click\",function(){\r\n");
      out.write("			var mbti_v=$(\"#mbti\").val();\r\n");
      out.write("			var s=\"<ol>\";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"get\",\r\n");
      out.write("				data:{\"mbti\":mbti_v},\r\n");
      out.write("				url:\"search/mbtiListProc.jsp\",\r\n");
      out.write("				dataType:\"json\",\r\n");
      out.write("				success:function(res){\r\n");
      out.write("					$.each(res, function(i,e){s+=\"<li>\"+e+\"</li>\";});\r\n");
      out.write("					s+=\"</ol>\";\r\n");
      out.write("					$(listDivs[1]).html(s);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			$(\"button.cancel\").trigger(\"click\");\r\n");
      out.write("		});\r\n");
      out.write("		$(buttonDivs[2]).on(\"click\",function(){\r\n");
      out.write("			var gender_v=$(\"#gender\").val();\r\n");
      out.write("			var s=\"<ol>\";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"get\",\r\n");
      out.write("				data:{\"gender\":gender_v},\r\n");
      out.write("				url:\"search/genderListProc.jsp\",\r\n");
      out.write("				dataType:\"json\",\r\n");
      out.write("				success:function(res){\r\n");
      out.write("					$.each(res, function(i,e){s+=\"<li>\"+e+\"</li>\";});\r\n");
      out.write("					s+=\"</ol>\";\r\n");
      out.write("					$(listDivs[2]).html(s);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			$(\"button.cancel\").trigger(\"click\");\r\n");
      out.write("		});\r\n");
      out.write("		$(buttonDivs[3]).on(\"click\",function(){\r\n");
      out.write("			var gender_v=$(\"#gender\").val();\r\n");
      out.write("			var s=\"<ol>\";\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"get\",\r\n");
      out.write("				data:{\"gender\":gender_v},\r\n");
      out.write("				url:\"search/areaListProc.jsp\",\r\n");
      out.write("				dataType:\"json\",\r\n");
      out.write("				success:function(res){\r\n");
      out.write("				    $.each(res, function(i,e){s+=\"<li>\"+e+\"</li>\";});\r\n");
      out.write("					s+=\"</ol>\";\r\n");
      out.write("					$(listDivs[3]).html(s);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("			$(\"button.cancel\").trigger(\"click\");\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	var subjectDivs = document.getElementsByClassName(\"subject\");\r\n");
      out.write("	\r\n");
      out.write("	var listDivs = document.getElementsByClassName(\"list\");\r\n");
      out.write("	var selectDivs = document.getElementsByClassName(\"select\");\r\n");
      out.write("	var buttonDivs = document.getElementsByClassName(\"attrsubmit\");\r\n");
      out.write("	var currentlyDisplayedList = null;\r\n");
      out.write("	var currentlyDisplayedSelect = null;\r\n");
      out.write("	var currentlyDisplayedButton = null;\r\n");
      out.write("	\r\n");
      out.write("	function showList(index) {\r\n");
      out.write("	\r\n");
      out.write("		// Hide the currently displayed list\r\n");
      out.write("		if (currentlyDisplayedList !== null) {\r\n");
      out.write("		currentlyDisplayedList.style.display = \"none\";\r\n");
      out.write("		}\r\n");
      out.write("		if (currentlyDisplayedList !== null) {\r\n");
      out.write("		currentlyDisplayedSelect.style.display = \"none\";\r\n");
      out.write("		}\r\n");
      out.write("		if (currentlyDisplayedList !== null) {\r\n");
      out.write("		currentlyDisplayedButton.style.display = \"none\";\r\n");
      out.write("		}\r\n");
      out.write("			  \r\n");
      out.write("		// Show the selected list\r\n");
      out.write("		listDivs[index].style.display = \"block\";\r\n");
      out.write("		currentlyDisplayedList = listDivs[index];\r\n");
      out.write("		selectDivs[index].style.display = \"block\";\r\n");
      out.write("		currentlyDisplayedSelect = selectDivs[index];\r\n");
      out.write("		buttonDivs[index].style.display = \"block\";\r\n");
      out.write("		currentlyDisplayedButton = buttonDivs[index];\r\n");
      out.write("		\r\n");
      out.write("		$(\"button.modalopen\").trigger(\"click\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function hideList() {\r\n");
      out.write("		currentlyDisplayedList.style.display = \"none\";\r\n");
      out.write("		currentlyDisplayedSelect.style.display = \"none\";\r\n");
      out.write("		currentlyDisplayedButton.style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"shape\">\r\n");
      out.write("		<div class=\"ptop\"><b>인기 검색어</b><span class=\"pspan\" style=\"float: right\"><i class=\"bi bi-backspace-fill pback\"></i></span></div>\r\n");
      out.write("		<div class=\"subject\">\r\n");
      out.write("			<span class=\"cat\" style=\"font-weight: 200; color: #9E9E9E;\">나이대별</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"list\">\r\n");
      out.write("		안녕하세요\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"subject\">\r\n");
      out.write("			<span class=\"cat\" style=\"font-weight: 200; color: #9E9E9E;\">mbti별</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"list\">\r\n");
      out.write("		2\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"subject\">\r\n");
      out.write("			<span class=\"cat\" style=\"font-weight: 200; color: #9E9E9E;\">성별</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"list\">\r\n");
      out.write("		3\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"subject\">\r\n");
      out.write("			<span class=\"cat\" style=\"font-weight: 200; color: #9E9E9E;\">지역별</span>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"list\">\r\n");
      out.write("		4\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"container mt-3\">\r\n");
      out.write("		<button type=\"button\" class=\"btn btn-primary modalopen\" data-bs-toggle=\"modal\" data-bs-target=\"#myModal\" style=\"visibility: hidden\"></button>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- The Modal -->\r\n");
      out.write("	<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("		<div class=\"modal-dialog modal-dialog-centered\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("			\r\n");
      out.write("				<!-- Modal Header -->\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h4 class=\"modal-title\">선택해주세요~!</h4>\r\n");
      out.write("					<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<!-- Modal body -->\r\n");
      out.write("				<div class=\"modal-body\">\r\n");
      out.write("					<div class=\"select\">\r\n");
      out.write("						<select id=\"age\">\r\n");
      out.write("							<option value=\"10\" selected>10대</option>\r\n");
      out.write("							<option value=\"20\">20대</option>\r\n");
      out.write("							<option value=\"30\">30대</option>\r\n");
      out.write("							<option value=\"40\">40대</option>\r\n");
      out.write("							<option value=\"50\">50대</option>\r\n");
      out.write("							<option value=\"60\">60대 이상</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"select\">\r\n");
      out.write("						<select id=\"mbti1\">\r\n");
      out.write("							<option value=\"e\" selected>E</option>\r\n");
      out.write("							<option value=\"i\">I</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<select id=\"mbti2\">\r\n");
      out.write("							<option value=\"n\" selected>N</option>\r\n");
      out.write("							<option value=\"s\">S</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<select id=\"mbti3\">\r\n");
      out.write("							<option value=\"t\" selected>T</option>\r\n");
      out.write("							<option value=\"f\">F</option>\r\n");
      out.write("						</select>\r\n");
      out.write("						<select id=\"mbti4\">\r\n");
      out.write("							<option value=\"p\" selected>P</option>\r\n");
      out.write("							<option value=\"j\">J</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"select\">\r\n");
      out.write("						<select id=\"gender\">\r\n");
      out.write("							<option value=\"male\" selected>남</option>\r\n");
      out.write("							<option value=\"female\">여</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"select\">\r\n");
      out.write("						<select id=\"area\">\r\n");
      out.write("							<option value=\"서울\" selected>서울특별시</option>\r\n");
      out.write("							<option value=\"인천\">인천광역시</option>\r\n");
      out.write("							<option value=\"경기\">경기도</option>\r\n");
      out.write("							<option value=\"강원\">강원도</option>\r\n");
      out.write("							<option value=\"충북\">충청북도</option>\r\n");
      out.write("							<option value=\"충남\">충청남도</option>\r\n");
      out.write("							<option value=\"광주\">광주광역시</option>\r\n");
      out.write("							<option value=\"전북\">전라북도</option>\r\n");
      out.write("							<option value=\"전남\">전라남도</option>\r\n");
      out.write("							<option value=\"대구\">대구광역시</option>\r\n");
      out.write("							<option value=\"부산\">부산광역시</option>\r\n");
      out.write("							<option value=\"경북\">경상북도</option>\r\n");
      out.write("							<option value=\"경남\">경상남도</option>\r\n");
      out.write("							<option value=\"제주\">제주도</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<!-- Modal footer -->\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-success attrsubmit\" id=\"ageBtn\">제출</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-success attrsubmit\" id=\"mbtiBtn\">제출</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-success attrsubmit\" id=\"genderBtn\">제출</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-success attrsubmit\" id=\"areaBtn\">제출</button>\r\n");
      out.write("					<button type=\"button\" class=\"btn btn-danger cancel\" data-bs-dismiss=\"modal\">취소</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
