/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.78
 * Generated at: 2023-09-21 01:37:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class loginForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로그인 페이지</title>\r\n");

String root = request.getContextPath();

      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("html {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	font-family: sans-serif;\r\n");
      out.write("	background: #fff;\r\n");
      out.write("	min-height: 100vh;\r\n");
      out.write("	background-image: url('");
      out.print(root);
      out.write("/jeju/b1.JPG');\r\n");
      out.write("	background-size: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box {\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	margin-top: 460px;\r\n");
      out.write("	margin-left: 920px;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	transform: translate(-50%, -50%);\r\n");
      out.write("	background: rgba(0, 0, 0, .5);\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	box-shadow: 0 15px 25px rgba(0, 0, 0, 0.5);\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box h2 {\r\n");
      out.write("	margin: 0 0 30px;\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .user-box {\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .user-box input {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 10px 0;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	margin-bottom: 30px;\r\n");
      out.write("	border: none;\r\n");
      out.write("	border-bottom: 1px solid #fff;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	background: transparent;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .user-box label {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	padding: 10px 0;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	pointer-events: none;\r\n");
      out.write("	transition: .5s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box .user-box input:focus ~ label, .login-box .user-box input:valid \r\n");
      out.write("	 ~ label {\r\n");
      out.write("	top: -20px;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	color: #03e9f4;\r\n");
      out.write("	font-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box form a {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	transition: .5s;\r\n");
      out.write("	margin-top: 40px;\r\n");
      out.write("	letter-spacing: 4px;\r\n");
      out.write("	width: 140px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a:hover {\r\n");
      out.write("	background: #03e9f4;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0\r\n");
      out.write("		100px #03e9f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a span:nth-child(1) {\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: -100%;\r\n");
      out.write("	width: 50px;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	background: linear-gradient(90deg, transparent, #03e9f4);\r\n");
      out.write("	animation: btn-anim1 1s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes btn-anim1 { 0% {\r\n");
      out.write("	left: -100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("50\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("%\r\n");
      out.write(",\r\n");
      out.write("100\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("%\r\n");
      out.write("{\r\n");
      out.write("left\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(":\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("100\r\n");
      out.write("%;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(".login-box a.button-signup {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	right: 10px; /* 수정: 오른쪽 정렬 */\r\n");
      out.write("	bottom: 10px; /* 수정: 아래 정렬 */\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	color: #03e9f4;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("	transition: .5s;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	letter-spacing: 4px;\r\n");
      out.write("	width: 140px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a.button-signup:hover {\r\n");
      out.write("	background: #03e9f4;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	box-shadow: 0 0 5px #03e9f4, 0 0 25px #03e9f4, 0 0 50px #03e9f4, 0 0\r\n");
      out.write("		100px #03e9f4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a.button-signup span {\r\n");
      out.write("	display: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box a.button-signup span:nth-child(1) {\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: -100%;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	background: linear-gradient(90deg, transparent, #03e9f4);\r\n");
      out.write("	animation: btn-anim1 1s linear infinite;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@\r\n");
      out.write("keyframes btn-anim1 { 0% {\r\n");
      out.write("	left: -100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("50\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("%\r\n");
      out.write(",\r\n");
      out.write("100\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("%\r\n");
      out.write("{\r\n");
      out.write("left\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(":\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("100\r\n");
      out.write("%;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(".login-box a.button-signup span:nth-child(2) {\r\n");
      out.write("	top: -100%;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	width: 2px;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: linear-gradient(180deg, transparent, #03e9f4);\r\n");
      out.write("	animation: btn-anim2 1s linear infinite;\r\n");
      out.write("	animation-delay: .25s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box button.button-login {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	color: #03e9f4;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	border: 2px solid #03e9f4;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: .5s;\r\n");
      out.write("	margin-top: 20px; /* Adjust the margin as needed */\r\n");
      out.write("	margin-right: 10px; /* Adjust the margin as needed */\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box button.button-login {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 10px 20px;\r\n");
      out.write("	color: #03e9f4;\r\n");
      out.write("	font-size: 16px;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	text-transform: uppercase;\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	border: 2px solid transparent; /* Transparent border initially */\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transition: .5s;\r\n");
      out.write("	margin-top: 20px; /* Adjust the margin as needed */\r\n");
      out.write("	margin-right: 10px; /* Adjust the margin as needed */\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box button.button-login:hover {\r\n");
      out.write("	background: #03e9f4;\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	border: 2px solid #03e9f4; /* Add border color on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box button.button-login::before {\r\n");
      out.write("	content: \"\";\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	border: 2px solid #03e9f4; /* Border color to match hover state */\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	transform: scale(0.8); /* Initial scale */\r\n");
      out.write("	opacity: 0; /* Initial opacity */\r\n");
      out.write("	transition: transform 0.3s ease, opacity 0.3s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box button.button-login:hover::before {\r\n");
      out.write("	transform: scale(1.2); /* Scale on hover */\r\n");
      out.write("	opacity: 1; /* Show on hover */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".login-box input[type=\"submit\"] {\r\n");
      out.write("	border: none;\r\n");
      out.write("	background: transparent;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	margin-left: 50px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@import url(//fonts.googleapis.com/earlyaccess/jejugothic.css);\r\n");
      out.write("body * { \r\n");
      out.write(" font-family: 'Jeju Gothic', sans-serif;\r\n");
      out.write(" background-color: \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");

String myid = (String) session.getAttribute("loginok");
String saveok = (String) session.getAttribute("saveok");
String sesave = (String) session.getAttribute("sesave");
//String memberid = (String)session.getAttribute("MEMBERID");

//boolean login = memberid==null?false:true;

boolean save = true;

if (saveok == null) {
	myid = "";
	save = false;
} else {
	save = true;
}

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"login-box\">\r\n");
      out.write("		<h2>Login</h2>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<form action=\"login/loginAction.jsp\" method=\"post\">\r\n");
      out.write("			<div class=\"user-box\">\r\n");
      out.write("				<input type=\"text\" name=\"id\" required=\"required\"\r\n");
      out.write("					value=\"");
      out.print(saveok == null ? "" : myid);
      out.write("\"> <label>ID</label>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"user-box\">\r\n");
      out.write("				<input type=\"password\" name=\"pass\" required=\"required\" size=\"15\">\r\n");
      out.write("				<label>Password</label><br>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<!-- 로그인 버튼 위치 수정하기 -->\r\n");
      out.write("			<button type=\"submit\" class=\"btn btn-info\"\r\n");
      out.write("				style=\"text-align: center; border: none; background: transparent; width: 100px; font-weight: bold; margin-left: 100px;\">Enter</button>\r\n");
      out.write("			<br>\r\n");
      out.write("\r\n");
      out.write("			<!-- TODO : 버튼 클릭시 아이디찾기랑 비밀번호 찾기 할 수 있게 구현하기. -->\r\n");
      out.write("			<br>\r\n");
      out.write("			<div\r\n");
      out.write("				style=\"display: flex; justify-content: center; margin-top: 10px;\">\r\n");
      out.write("				<button type=\"button\"\r\n");
      out.write("					style=\"border: none; background: transparent; width: 100px; font-weight: bold; margin-left: 8px;\">\r\n");
      out.write("					<b style=\"font-size: 13px;\">아이디찾기</b>\r\n");
      out.write("				</button>\r\n");
      out.write("				<button type=\"button\"\r\n");
      out.write("					style=\"border: none; background: transparent; width: 110px; font-weight: bold; margin-left: 10px;\">\r\n");
      out.write("					<b style=\"font-size: 13px;\">비밀번호찾기</b>\r\n");
      out.write("				</button>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<a class=\"button-signup\" href=\"index.jsp?main=member/Gaipform.jsp\"><b>회원가입</b></a>\r\n");
      out.write("\r\n");
      out.write("			<br> <br> <input type=\"checkbox\" name=\"cbsave\"\r\n");
      out.write("				");
      out.print(saveok == null ? "" : "checked");
      out.write("><b\r\n");
      out.write("				style=\"font-size: 14px;\">아이디저장</b>&nbsp;&nbsp; <input\r\n");
      out.write("				type=\"checkbox\" name=\"sesave\" ");
      out.print(sesave == null ? "" : "checked");
      out.write("><b\r\n");
      out.write("				style=\"font-size: 14px;\">로그인상태유지</b>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
